version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pharm:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"

  migrations:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  loaddata:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      migrations:
        condition: service_completed_successfully
    command:
      - python manage.py loaddata fixtures/tovar_ready.json
      - python manage.py loaddata fixtures/tovar_client_ready.json


  api:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
        migrations:
          condition: service_completed_successfully

volumes:
  pharm: