# Generated by Django 4.2.4 on 2023-08-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ean13', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Штрих-код')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование товара')),
                ('ean13', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='names', to='products.product', verbose_name='Штрих-код')),
            ],
            options={
                'verbose_name': 'Клиентский товар',
                'verbose_name_plural': 'Клиентские товары',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('names', models.ManyToManyField(blank=True, null=True, to='products.productclient', verbose_name='Клиентское наименование товара')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Распределение товаров',
                'verbose_name_plural': 'Распределение товаров',
            },
        ),
    ]
