# Generated by Django 4.2.4 on 2023-08-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='names',
        ),
        migrations.AddField(
            model_name='productclient',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='products.distribution'),
        ),
    ]
