# Generated by Django 4.2.4 on 2023-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_distribution_names_productclient_distribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Стыковка товаров', 'verbose_name_plural': 'Стыковка товаров'},
        ),
        migrations.AlterModelOptions(
            name='productclient',
            options={'verbose_name': 'Пользовательский товар', 'verbose_name_plural': 'Пользовательские товары'},
        ),
        migrations.RenameField(
            model_name='productclient',
            old_name='ean13',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productclient',
            name='distribution',
        ),
        migrations.AlterField(
            model_name='productclient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Пользовательское наименование товара'),
        ),
    ]
