# Generated by Django 4.2.4 on 2023-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_distribution_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_prep',
        ),
        migrations.RenameField(
            model_name='productclient',
            old_name='name',
            new_name='name_prep',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
    ]
