# Generated by Django 4.2.4 on 2023-08-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_productclient_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='product',
            field=models.OneToOneField(auto_created=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
    ]
