# Generated by Django 4.2.4 on 2023-08-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_distribution_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар'),
        ),
    ]
