# Generated by Django 4.2.4 on 2023-08-24 12:26

import django.core.validators
from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_distribution_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean13',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9]{13}$'), products.validators.validate_ean13], verbose_name='Штрих-код'),
        ),
    ]
